Revisions to glyma.Chen_Fang_2019.yml on 26 April 2024
legumeinfo/gene-function-registry pull request #42
Opened 2024-04-26 22:48 UTC by ScottKalberer

I've updated the gene_function_registry file glyma.Chen_Fang_2019.yml, created the new branch glyma.Chen_Fang_2019, and pushed everything to the GitHub origin. This entity was originally created by Greg Murrell.  I'm requesting review of this YML gene function file, merge of the changes into main branch, and subsequent deletion of this temporary branch on GitHub.

2024-05-01 14:29 UTC, StevenCannon-USDA submitted a review, later dismissed

2024-05-01 14:34 UTC, StevenCannon-USDA requested changes
Please remove the extraneous space after `phenotype_synopsis:`
(picky, but triggers an error in yamllint)

2024-05-01 14:34 UTC, StevenCannon-USDA commented on Glycine/max/studies/glyma.Chen_Fang_2019.yml
Generally looks good, but line 20 generates a yamllint error. You can fix it by removing one of the spaces after `phenotype_synopsis:`

2024-05-01 21:56 UTC, ScottKalberer commented on Glycine/max/studies/glyma.Chen_Fang_2019.yml
I have removed the extraneous space following the phenotype_synopsis:.  However, I could not get yamllint to produce an error message using this file, regardless of how many extra spaces I added.  Perhaps there's a setting on their website that I need to adjust to see this problem?

2024-05-01 21:59 UTC, ScottKalberer commented
Hi Steven, I removed the unwanted space from the gene function file Chen_Fang_2019.yml.  Please approve this pull request and merge if you are satisfied.

2024-05-02 13:33 UTC, StevenCannon-USDA approved these changes

2024-05-02 13:33 UTC, merged

2024-05-02 13:33 UTC, StevenCannon-USDA commented
The latest changes seem to have taken care of the yamllint complaints.